### ISSUE TITLE
64 hashing results

### ISSUE THREAD

**Issue by XuZhang2** [qliu24/SAKE#5]
Hello, How could I reproduce the mAP and Precision results with features represented by 64d hashing code.  I didn't find codes about itq etc.

**Comment by qliu24** [comment]
Hi, for iterative quantization, we used the code from: https://slazebni.cs.illinois.edu/research/smallcode.zip

**Comment by develop-productivity** [comment]
> Hi, for iterative quantization, we used the code from: https://slazebni.cs.illinois.edu/research/smallcode.zip

Hi, I found this piece of code to get the hashing code. Do you use the 64-dimensional features extracted by it to directly obtain the map index when the Hashing Code Dimension = 64? Or you have another process for calculating ITQ that is not reflected in the code
https://github.com/qliu24/SAKE/blob/aad0fe3236c63fff7875ad0ad6e8ba2e59a05fef/src/test_cse_resnet_sketchy_zeroshot.py#L273

**Comment by qliu24** [comment]
Sorry, the work was done three years ago and I cannot recall all the implementation details. The code shared in my previous answer is the one we used to calculate ITQ.

**Comment by develop-productivity** [comment]
> Sorry, the work was done three years ago and I cannot recall all the implementation details. The code shared in my previous answer is the one we used to calculate ITQ.

I'm sorry to bother you again, I have another question. Since you only provided pre-training weights for the model 'CSEResnetModel _ KDHashing'. Did you use only 'CSEResnetModel _ KDHashing' to test the metrics for the hash code dimension = 64 and the no hash code case during training? Or did you use 'CSEResnetModel _ KD' to test the metrics without hash codes? These are my questions, thank you for your help!
